# Generated by Django 5.0.6 on 2024-07-02 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.BinaryField(blank=True, null=True)),
                ('rowstatus', models.BooleanField(default=True)),
            ],
        ),
    ]
