# Generated by Django 5.0.6 on 2024-07-02 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idscore', '0001_initial'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        
        
        
    ]
