# Generated by Django 5.0.6 on 2024-06-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idsproductdetails',
            options={'permissions': [('can_view_all_products', 'Can view all products')]},
        ),
    ]
