# Generated by Django 5.0.6 on 2024-06-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_rename_username_login_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='name',
            new_name='username',
        ),
    ]
