# Generated by Django 5.0.6 on 2024-06-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_rename_name_login_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='name',
        ),
    ]
