# Generated by Django 5.0.6 on 2024-06-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Object_Detection', '0003_alter_idsproductdetails_productid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idsproductdetails',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='idsproductdetails',
            name='item',
            field=models.TextField(),
        ),
    ]
