# Generated by Django 5.0.6 on 2024-06-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Object_Detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDSProductDetails',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('units', models.IntegerField()),
                ('thresholdValue', models.IntegerField()),
                ('images', models.JSONField(default=list)),
            ],
        ),
    ]
