# Generated by Django 5.0.6 on 2024-06-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Object_Detection', '0005_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IDSProductDetails',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
